// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBo2_c2O6HmcnvWXVH5R7lZwZY_WML4_Qo',
    appId: '1:805066321918:web:f3df3e083f4e18496a1aaf',
    messagingSenderId: '805066321918',
    projectId: 'smart-stitch-ai',
    authDomain: 'smart-stitch-ai.firebaseapp.com',
    storageBucket: 'smart-stitch-ai.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEa69CPGpJTvAblb2qYLZOM2ubaRjho2Y',
    appId: '1:805066321918:android:dd7be831a2e5a5c46a1aaf',
    messagingSenderId: '805066321918',
    projectId: 'smart-stitch-ai',
    storageBucket: 'smart-stitch-ai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAtoduEx5phXPoYt3HiwvFCmAJd_OYW4c',
    appId: '1:805066321918:ios:4ac437ab6c3bf4686a1aaf',
    messagingSenderId: '805066321918',
    projectId: 'smart-stitch-ai',
    storageBucket: 'smart-stitch-ai.firebasestorage.app',
    iosBundleId: 'com.example.smartStitchedAi1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBo2_c2O6HmcnvWXVH5R7lZwZY_WML4_Qo',
    appId: '1:805066321918:web:67a9cd93b896bef36a1aaf',
    messagingSenderId: '805066321918',
    projectId: 'smart-stitch-ai',
    authDomain: 'smart-stitch-ai.firebaseapp.com',
    storageBucket: 'smart-stitch-ai.firebasestorage.app',
  );
}
